[tool.poetry]
name = "lib-avstack-core"
version = "0.1.0-alpha.1"
description = "Core library for autonomous vehicle development"
authors = ["Spencer Hallyburton <spencer.hallyburton@duke.edu>"]
readme = "README.md"
license = "Apache-2.0"
homepage = "https://avstack.org"
repository = "https://github.com/avstack-lab/lib-avstack-core"
keywords = ["self-driving", "autonomy", "perception", "planning", "control"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
]
packages = [{include = "avstack"}]
include = ["CHANGELOG.md"]

[tool.poetry.dependencies]
python = "~3.10"
numpy = ">=1.20, <1.24"
filterpy = "^1"
scipy = "^1.9"
cython = "^0.29"
numpy-quaternion = "^2022.4"
numba = "~0.57.1"
seaborn = "~0.12.2"
albumentations = "~1.3.1"
Pillow = "^9"
opencv-python = ">=4.3, <4.7"
tqdm = "^4"
scikit-learn = "^1.1"
torch = { url = "https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl" }
torchvision = { url = "https://download.pytorch.org/whl/cu117/torchvision-0.14.1%2Bcu117-cp310-cp310-linux_x86_64.whl" }
mmcv = { url = "https://g-b0ef78.1d0d8d.03c0.data.globus.org/packages/mmcv/torch1.13.1_cu11.7/mmcv-2.0.1-cp310-cp310-linux_x86_64.whl" }
#mmcv = { url = "https://download.openmmlab.com/mmcv/dist/cu113/torch1.10.0/mmcv-2.0.0-cp39-cp39-manylinux1_x86_64.whl" }
mmengine = "^0.7.3"
mmsegmentation = { path = "./third_party/mmsegmentation", develop = true }
mmdet = { path = "./third_party/mmdetection/", develop = true }
mmdet3d = { path = "./third_party/mmdetection3d/", develop = true }
midas = {path = "./third_party/MiDaS/", develop=true }

[tool.poetry.group.serve.dependencies]
torchserve = "~0.8.2"
torch-model-archiver = "~0.8.2"
torch-workflow-archiver = "~0.2.10"
nvgpu = "~0.10.0"

[tool.poetry.group.docs.dependencies]
mkdocstrings-python = "^0.8.3"
mkdocs-material = "^9.0"

[tool.poetry.group.test.dependencies]
pytest = "^7"
pytest-cov = "^4"
bandit = "^1.7"
black = "~22.12.0"
mypy = "^0"
isort = "^5.11"
flake8 = "^5.0"
autoflake = "^1"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -s"
testpaths = [
    "tests",
    "integration",
]

[build-system]
requires = [
    "poetry-core",
]
build-backend = "poetry.core.masonry.api"
